# Generated by Django 5.2.14 on 2026-05-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('kienyeji', 'Kienyeji'), ('broiler', 'Broiler'), ('layer', 'Layer')], max_length=50)),
                ('initial_count', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('harvested', 'Harvested'), ('closed', 'Closed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('birds_sold', models.PositiveIntegerField()),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='chickens.batch')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_consumed_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('average_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='chickens.batch')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
